# Generated by Django 5.1.4 on 2025-01-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'can send private email to customers.')]},
        ),
    ]
